import { Link } from "wouter";
import { useEffect, useState } from "react";
import {
  Download,
  FileCode2,
  FileJson,
  Trash2,
  Lock,
  AlertCircle,
  CheckCircle2,
  ArrowLeft,
  Save,
} from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { fullDisplayName, getPerson, people, families, stats, type Person } from "@/lib/family";
import { useEdit, type PersonPatch } from "@/components/EditContext";

interface FieldDiff {
  field: string;
  before: string;
  after: string;
}

function fmt(v: unknown): string {
  if (v == null) return "—";
  if (typeof v === "string") return v || "—";
  if (Array.isArray(v)) {
    if (v.length === 0) return "(empty)";
    return v
      .map((item) => {
        if (typeof item === "string") return item;
        if (item && typeof item === "object") {
          // Affiliation or Source-like
          const r = item as Record<string, unknown>;
          if ("title" in r || "url" in r) {
            return [r.title, r.url].filter(Boolean).join(" · ");
          }
          if ("name" in r || "key" in r) {
            return [r.name || r.key, r.role, r.dates].filter(Boolean).join(" · ");
          }
        }
        return JSON.stringify(item);
      })
      .join("\n");
  }
  if (typeof v === "object") {
    const o = v as Record<string, unknown>;
    if ("date" in o || "place" in o) {
      const parts = [o.date, o.place].filter(Boolean) as string[];
      return parts.length ? parts.join(" · ") : "—";
    }
    return JSON.stringify(v);
  }
  return String(v);
}

function diffPatch(original: Person | undefined, patch: PersonPatch): FieldDiff[] {
  const out: FieldDiff[] = [];
  const before = (original ?? {}) as Record<string, unknown>;
  for (const k of Object.keys(patch) as (keyof PersonPatch)[]) {
    const a = before[k];
    const b = (patch as Record<string, unknown>)[k];
    if (JSON.stringify(a) === JSON.stringify(b)) continue;
    out.push({ field: k, before: fmt(a), after: fmt(b) });
  }
  return out;
}

function buildMergedDataJson(pending: Record<string, PersonPatch>) {
  const individuals = people.map((p) => {
    const patch = pending[p.id];
    if (!patch) return p;
    return { ...p, ...patch };
  });
  return {
    individuals,
    families,
    stats,
  };
}

function pythonRepr(value: unknown): string {
  if (value === null || value === undefined) return "None";
  if (typeof value === "boolean") return value ? "True" : "False";
  if (typeof value === "number") return String(value);
  if (typeof value === "string") {
    // Use json.dumps-style escape: backslash and double-quote
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) {
    return "[" + value.map(pythonRepr).join(", ") + "]";
  }
  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>).map(
      ([k, v]) => `${JSON.stringify(k)}: ${pythonRepr(v)}`,
    );
    return "{" + entries.join(", ") + "}";
  }
  return "None";
}

function buildPatchScript(pending: Record<string, PersonPatch>): string {
  const ts = new Date().toISOString();
  const lines: string[] = [
    "#!/usr/bin/env python3",
    `# Auto-generated by the in-app editor on ${ts}.`,
    "# Apply pending field edits to client/src/data.json.",
    "# Run from project root:  python3 apply_changes.py",
    "",
    "import json, sys",
    "from pathlib import Path",
    "",
    'DATA = Path("client/src/data.json")',
    "",
    "PATCHES = " + pythonRepr(pending),
    "",
    "def main():",
    '    if not DATA.exists():',
    '        sys.exit(f"data.json not found at {DATA}")',
    '    data = json.loads(DATA.read_text())',
    "    by_id = {p['id']: p for p in data['individuals']}",
    "    touched = 0",
    "    for pid, patch in PATCHES.items():",
    "        person = by_id.get(pid)",
    "        if not person:",
    '            print(f"  skip: {pid} not found")',
    "            continue",
    "        for key, value in patch.items():",
    "            person[key] = value",
    "        touched += 1",
    '    DATA.write_text(json.dumps(data, indent=2, ensure_ascii=False))',
    '    print(f"Applied {touched} patches to {DATA}")',
    "",
    'if __name__ == "__main__":',
    "    main()",
    "",
  ];
  return lines.join("\n");
}

function download(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export default function Changes() {
  const { unlocked, pending, discard, discardAll, count } = useEdit();
  const [backendAvailable, setBackendAvailable] = useState<boolean | null>(null);
  const [saving, setSaving] = useState(false);
  const [savedMessage, setSavedMessage] = useState<string | null>(null);
  const [saveError, setSaveError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetch("/api/data", { method: "HEAD" })
      .then((r) => {
        if (!cancelled) setBackendAvailable(r.ok);
      })
      .catch(() => {
        if (!cancelled) setBackendAvailable(false);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  async function saveToBackend() {
    setSaving(true);
    setSaveError(null);
    setSavedMessage(null);
    try {
      const body = buildMergedDataJson(pending);
      const r = await fetch("/api/data", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      if (!r.ok) throw new Error(`Server responded ${r.status}`);
      setSavedMessage("Saved to client/src/data.json. Reload the dev server to see updates in code.");
      discardAll();
    } catch (e) {
      setSaveError(e instanceof Error ? e.message : "Save failed");
    } finally {
      setSaving(false);
    }
  }

  if (!unlocked && count === 0) {
    return (
      <div className="mx-auto max-w-3xl px-4 sm:px-5 py-12">
        <Card className="border-card-border">
          <CardContent className="p-6 text-center">
            <Lock className="h-6 w-6 text-muted-foreground mx-auto mb-3" />
            <h1 className="font-display text-xl font-semibold">Edit mode is locked</h1>
            <p className="text-sm text-muted-foreground mt-2">
              Unlock edit mode from the header to begin staging changes.
            </p>
            <Link
              href="/"
              className="inline-flex items-center gap-1 mt-4 text-sm text-primary hover:underline"
            >
              <ArrowLeft className="h-3 w-3" /> Back to home
            </Link>
          </CardContent>
        </Card>
      </div>
    );
  }

  const entries = Object.entries(pending);

  return (
    <div className="mx-auto max-w-4xl px-4 sm:px-5 py-6 sm:py-8">
      <Link
        href="/"
        className="inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground mb-4"
      >
        <ArrowLeft className="h-3 w-3" /> Back
      </Link>

      <header className="mb-6 sm:mb-8">
        <h1 className="font-display text-xl font-semibold">Pending changes</h1>
        <p className="text-sm text-muted-foreground mt-1">
          {count === 0
            ? "No edits staged yet. Open a person and click any field's pencil to begin."
            : `${count} ${count === 1 ? "person" : "people"} touched. Review below, then save or download.`}
        </p>
      </header>

      {count > 0 && (
        <div className="mb-6 flex flex-wrap items-center gap-2">
          {backendAvailable && (
            <Button
              onClick={saveToBackend}
              disabled={saving}
              data-testid="button-save-disk"
              className="gap-2"
            >
              <Save className="h-4 w-4" /> {saving ? "Saving…" : "Save to data.json"}
            </Button>
          )}
          <Button
            variant="outline"
            onClick={() =>
              download("data.json", JSON.stringify(buildMergedDataJson(pending), null, 2), "application/json")
            }
            data-testid="button-download-json"
            className="gap-2"
          >
            <FileJson className="h-4 w-4" /> Download data.json
          </Button>
          <Button
            variant="outline"
            onClick={() => download("apply_changes.py", buildPatchScript(pending), "text/x-python")}
            data-testid="button-download-script"
            className="gap-2"
          >
            <FileCode2 className="h-4 w-4" /> Download apply_changes.py
          </Button>
          <Button
            variant="ghost"
            onClick={() => {
              if (window.confirm(`Discard all ${count} pending changes?`)) {
                discardAll();
              }
            }}
            data-testid="button-discard-all"
            className="gap-2 text-muted-foreground"
          >
            <Trash2 className="h-4 w-4" /> Discard all
          </Button>
        </div>
      )}

      {savedMessage && (
        <div
          className="mb-4 flex items-start gap-2 rounded-md border border-primary/30 bg-primary/5 p-3 text-sm text-primary"
          data-testid="text-save-success"
        >
          <CheckCircle2 className="h-4 w-4 mt-0.5 shrink-0" />
          <span>{savedMessage}</span>
        </div>
      )}
      {saveError && (
        <div
          className="mb-4 flex items-start gap-2 rounded-md border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive"
          data-testid="text-save-error"
        >
          <AlertCircle className="h-4 w-4 mt-0.5 shrink-0" />
          <span>{saveError}</span>
        </div>
      )}

      {backendAvailable === false && count > 0 && (
        <div className="mb-4 flex items-start gap-2 rounded-md border border-border bg-muted/40 p-3 text-xs text-muted-foreground">
          <Download className="h-4 w-4 mt-0.5 shrink-0" />
          <span>
            No local backend detected. Use the download buttons to grab a new <code>data.json</code> or an
            <code> apply_changes.py</code> patch script you can run in your repo.
          </span>
        </div>
      )}

      <div className="space-y-4">
        {entries.map(([id, patch]) => {
          const original = getPerson(id);
          const diffs = diffPatch(original, patch);
          return (
            <Card key={id} className="border-card-border" data-testid={`change-${id}`}>
              <CardContent className="p-4 sm:p-5">
                <div className="flex items-start justify-between gap-3 mb-3">
                  <div className="min-w-0">
                    <Link
                      href={`/person/${encodeURIComponent(id)}`}
                      className="font-display text-base font-semibold hover:underline break-words"
                    >
                      {original ? fullDisplayName(original) : id}
                    </Link>
                    <div className="text-[10px] uppercase tracking-[0.16em] text-muted-foreground mt-0.5">
                      <span className="font-mono normal-case tracking-normal">{id}</span> ·{" "}
                      {diffs.length} {diffs.length === 1 ? "field" : "fields"}
                    </div>
                  </div>
                  <button
                    type="button"
                    onClick={() => discard(id)}
                    className="shrink-0 inline-flex h-7 w-7 items-center justify-center rounded text-muted-foreground hover:text-destructive hover-elevate active-elevate-2"
                    aria-label="Discard this person's edits"
                    data-testid={`change-${id}-discard`}
                  >
                    <Trash2 className="h-3.5 w-3.5" />
                  </button>
                </div>
                <ul className="space-y-2">
                  {diffs.map((d) => (
                    <li key={d.field} className="text-sm">
                      <div className="text-[10px] uppercase tracking-[0.16em] text-muted-foreground mb-1">
                        {d.field}
                      </div>
                      <div className="grid sm:grid-cols-2 gap-2">
                        <div className="rounded border border-card-border bg-muted/30 p-2">
                          <div className="text-[10px] text-muted-foreground mb-0.5">Before</div>
                          <div className="whitespace-pre-line break-words text-muted-foreground">
                            {d.before}
                          </div>
                        </div>
                        <div className="rounded border border-primary/30 bg-primary/5 p-2">
                          <div className="text-[10px] text-primary/80 mb-0.5">After</div>
                          <div className="whitespace-pre-line break-words">{d.after}</div>
                        </div>
                      </div>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          );
        })}
      </div>
    </div>
  );
}
